app/models.py
from flask_sqlalchemy import SQLAlchemy
from app import app
from config import ProductionConfig
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login
from datetime import datetime



app.config.from_object(ProductionConfig)
db = SQLAlchemy(app) #adding app to sqlalchemy databaase







class Name(db.Model): #model for database
    id = db.Column(db.Integer , primary_key=True)#we have to specify pk manually
    name =db.Column(db.String(200))
    surname=db.Column(db.String(300))
    age = db.Column(db.Integer)


    def __repr__(self): 
        #this acts like __str__ of django
        return f'<Name {self.name}>'


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100))
    username = db.Column(db.String(50), nullable=False, unique=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    password_hash = db.Column(db.String(100), nullable=False)
    created_on = db.Column(db.DateTime(), default=datetime.utcnow)
    updated_on = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)
 
    def __repr__(self):
        return "<{}:{}>".format(self.id, self.username)
 
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
 
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, IntegerField , SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User





class NameForm(FlaskForm):
    name = StringField('Name' , validators=[DataRequired(message='Name should not be empty')])
    surname = StringField('SurName' , validators = [DataRequired(message='Surname Should not be empty')])
    age = IntegerField('Age' , validators=[DataRequired(message='Age must be int')])




class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')




class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

app/__init__.py
from flask import Flask
from flask_login import LoginManager

#create app
app = Flask(__name__) #init app
app.config['SECRET_KEY'] = 'any string works here'

#register login
login = LoginManager(app)
login.init_app(app)


login.login_view = 'user.login' #redirect users to login view if they are not logged in


# register blueprints
from .user import user as user_blueprint
app.register_blueprint(user_blueprint)

from app import views #importing views 

views.app #running views

app/user/__init__.py
from flask import Blueprint #importing blueprint
 
user = Blueprint('user', __name__,template_folder='templates',static_folder='static') #using blueprint



from . import views

app/user/views.py
from . import user
from ..forms import RegistrationForm , LoginForm
from ..models import User, db
from flask import redirect , url_for , flash , render_template
from flask_login import logout_user , login_user ,current_user, login_required









@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('home'))
    return render_template('login.htm', form=form)




@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))



@user.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('user.login'))
    return render_template('register.htm', title='Register', form=form)

app/views.py
from flask import render_template,request , redirect , url_for , flash
from app import app
from app.forms import NameForm
from app.models import Name ,db
from flask_login import login_required





@app.route('/')
def home():
    names = Name.query.all()
    total_users = len(names)
    return render_template('home.htm' , names=names , total=total_users)



@app.route('/form' , methods=['GET', 'POST'])
@login_required
def form():
    form= NameForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            name = request.form['name']
            surname = request.form['surname']
            age = request.form['age'] 
            user = Name(name = name , surname=surname , age=age)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('home'))
    return render_template('nameform.htm' , form=form)





@app.route('/deleteform/<int:id>' , methods=['GET' , 'POST'])
@login_required
def deleteform(id):
    query = Name.query.get(id)
    if request.method == 'POST':
        db.session.delete(query)
        db.session.commit()
        return redirect(url_for('home'))
    return render_template('deleteform.htm' , data=query)





@app.route('/detailform/<int:id>')
@login_required
def detailform(id):
    query= Name.query.get(id)
    return render_template('detailform.htm' , data=query)



@app.route("/updateform/<int:id>", methods=["GET","POST"])
def updateform(id):
    query = Name.query.get(id)
    if query:
        form = NameForm(request.form,obj=query)
        if request.method == 'POST' and form.validate_on_submit:
            name = request.form['name']
            surname = request.form['surname']
            age = request.form['age']
            query.name = name
            query.surname = surname
            query.age = age
            db.session.add(query)
            db.session.commit()
            flash('Name updated successfully')
            return redirect(url_for('home'))
    return render_template('updateform.htm', form=form)

main.py
from app import app





if __name__ == '__main__':
    app.run(debug=True , port=8000)

app/templates/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>

    {% block content %}

    {% endblock %}



    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/deleteform.htm
{% extends 'base.htm' %}



{% block title %}Delete {% endblock %}



{% block content %}

<form method="POST">
    <p>Are you sure wanna delete {{data.name}}?</p>
    <button type="submit">Yes</button>
    <a href="{{url_for('detailform' , id=data.id)}}"><button type="button">No</button></a>
</form>

{% endblock %}

app/templates/detailform.htm
{% extends 'base.htm' %}




{% block title %} Details {% endblock %}

{% block content %}

<h1>Name:{{data.name}}</h1>
<p>Surname:{{data.surname}}</p>
<p>Age:{{data.age}}</p>


<a href="{{url_for('updateform' , id=data.id)}}"><button>Update</button></a>
<a href="{{url_for('deleteform' , id=data.id)}}"><button>Delete</button></a>
<a href="{{url_for('home')}}">Go Back</a>
{% endblock %}

app/templates/home.htm
{% extends 'base.htm' %}


{% block title %} Homepage {% endblock title %}


{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  {% endif %}
{% endwith %}
{% if current_user.is_authenticated %}
<p>Welcome {{current_user.username}}</p>

<a href="{{url_for('user.logout')}}">Log Out</a>
<br>
{% endif %}
<a href="{{url_for('form')}}"> Add User</a>
{% if names %}

{% for name in names %}
<ul>
    <a href="{{url_for('detailform' , id=name.id)}}"><h1>Name:{{name.name}}</h1></a>
</ul>

{% endfor %}
{% endif %}

<br>
<p>Total Users: {{total}}</p>
{% endblock content %}

app/templates/login.htm
{% extends 'base.htm' %}



{% block title %}Login {% endblock %}


{% block content %}


    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New User? <a href="{{ url_for('user.register') }}">Click to Register!</a></p>

{% endblock %}

app/templates/nameform.htm
{% extends 'base.htm' %}

{% block title %} NameForm {% endblock %}


{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  {% endif %}
{% endwith %}
<p>Hi , add Names here</p>
<a href="{{url_for('home')}}">Back</a>
<form method="POST" novalidate>
        {{form.hidden_tag()}}
        <p>
          {{form.name.label()}}
          {{form.name()}}
          {% for error in form.name.erros %}
        {{error}}
        {% endfor%}
        </p>
        <p>
          {{form.surname.label()}}
          {{form.surname()}}
          {% for error in form.surname.erros %}
          {{error}}
          {% endfor %}
        </p>
        <p>
          {{form.age.label()}}
          {{form.age()}}
          <ul>
            {% for error in form.age.errors %}

              <div class="alert alert-danger" role="alert">
                  {{error}}
                </div>
                
                {% endfor %}
            
          </ul>
         
        </p>
        <button type="submit">Save</button>

</form>

{% endblock %}

app/templates/register.htm
{% extends "base.htm" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/updateform.htm
{% extends 'base.htm' %}

{% block title %} NameForm {% endblock %}


{% block content %}

<a href="{{url_for('home')}}">Back</a>
<form method="POST" novalidate>
        {{form.hidden_tag()}}
        <p>
          {{form.name.label()}}
          {{form.name()}}
          {% for error in form.name.erros %}
        {{error}}
        {% endfor%}
        </p>
        <p>
          {{form.surname.label()}}
          {{form.surname()}}
          {% for error in form.surname.erros %}
          {{error}}
          {% endfor %}
        </p>
        <p>
          {{form.age.label()}}
          {{form.age()}}
          <ul>
            {% for error in form.age.errors %}

              <div class="alert alert-danger" role="alert">
                  {{error}}
                </div>
                
                {% endfor %}
            
          </ul>
         
        </p>
        <button type="submit">Update</button>

</form>

{% endblock %}